psql wikidata_entities < monthly_edit_types.sql
psql wikidata_entities < monthly_misalignment_and_edits_ordered_by_entity_year_month.sql
psql wikidata_entities < edit_proportions_by_entity_views_5_17.sql
psql wikidata_entities < edit_proportions_by_quality_and_view_class_5_17.sql
psql wikidata_entities < edit_proportions_by_quality_class_5_17.sql