# Have been running on the virtual environment on flagon here: /export/scratch2/wmf/scripts/

set wikidata_page_revisions_with_timestamp_edit_types_and_usage_table_queries_directory = /export/scratch2/wmf/scripts/wikidata_usage_tracking/sql_scripts/postgres/wikidata_page_revisions_with_timestamp_table/wikidata_page_revisions_bot_info_table/wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_table/wikidata_page_revisions_with_timestamp_edit_types_and_usage_table/queries

set sql_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage
set post_processing_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/wikidata_page_revisions_with_timestamp_edit_types_and_usage

set wikidata_page_revisions_with_timestamp_edit_types_and_usage_sql_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage
set wikidata_page_revisions_with_timestamp_edit_types_and_usage_processing_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/wikidata_page_revisions_with_timestamp_edit_types_and_usage



psql wikidata_entities < $wikidata_page_revisions_with_timestamp_edit_types_and_usage_table_queries_directory/edit_type_sums.sql
psql wikidata_entities < $wikidata_page_revisions_with_timestamp_edit_types_and_usage_table_queries_directory/random_revisions.sql
psql wikidata_entities < $wikidata_page_revisions_with_timestamp_edit_types_and_usage_table_queries_directory/semi_automated_revision_word_counts.sql

