\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%#quickstatements%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_1.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%#petscan%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_2.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%#autolist2%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_3.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%talkgadgetautoeditjs|autoedit]]%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_4.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%labellister%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_5.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%#itemcreator%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_6.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%#dragrefjs%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_7.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%[[useryms/lc|lcjs]]%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_8.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%#wikidatagame%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_9.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%[[wikidataprimary%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_10.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%mix''n''match%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_11.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%#distributedgame%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_12.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%[[userjitrixis/nameguzzlerjs|nameguzzler]]%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_13.tsv';

\copy (select comment from wikidata_page_revisions_with_timestamp_edit_types_and_usage where lower(regexp_replace(comment, '\.|,|\(|\)|-|:','','g')) LIKE '%[[mediawikigadgetmergejs|mergejs]]%' AND page_views IS NOT NULL order by random() limit 100) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage/random_revisions_14.tsv';
