CREATE INDEX entity_revisions_and_bot_flags_and_tool_change_tags_index ON entity_revisions_and_bot_flags_and_tool_change_tags(revision_timestamp);
CREATE INDEX entity_revisions_and_bot_flags_and_tool_change_tags_index ON entity_revisions_and_bot_flags_and_tool_change_tags(page_title);
CREATE INDEX entity_revisions_and_bot_flags_and_tool_change_tags_index ON entity_revisions_and_bot_flags_and_tool_change_tags(revision_id);
CREATE INDEX entity_revisions_and_bot_flags_and_tool_change_tags_index ON entity_revisions_and_bot_flags_and_tool_change_tags(revision_user);
CREATE INDEX entity_revisions_and_bot_flags_and_tool_change_tags_index ON entity_revisions_and_bot_flags_and_tool_change_tags(comment);
