set sql_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_edit_types_and_usage
set post_processing_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/wikidata_page_revisions_with_timestamp_edit_types_and_usage

psql wikidata_entities < all_edits_for_used_entities.sql

mwsessions sessionize $sql_results_directory/all_edits_for_used_entities.tsv --events=$post_processing_results_directory/all_revision_session_data.tsv --verbose > $post_processing_results_directory/all_session_data.tsv

python /export/scratch2/wmf/scripts/wikidata_usage_tracking/python_analysis_scripts/session_analysis/session_analyzer.py $post_processing_results_directory/all_revision_session_data.tsv $post_processing_results_directory/all_events_session_mean_frequency_edits.tsv --verbose
