# Have been running on the virtual environment on flagon here: /export/scratch2/wmf/scripts/
source all_edits_for_used_entities_query_and_post_processing.sh
source anon_edits_for_used_entities_query_and_post_processing.sh
source registered_users_edits_for_used_entities_query_and_post_processing.sh
psql wikidata_entities < all_edits_for_used_entities.sql
psql wikidata_entities < edit_type_sums.sql
psql wikidata_entities < random_revisions.sql
psql wikidata_entities < semi_automated_revision_word_counts.sql