# Bot edits
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '1' as period FROM misalignment_and_edits where revision_timestamp >= 20130500000000 and revision_timestamp < 20140500000000 AND page_views IS NOT NULL AND edit_type = 'bot_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_bot_edits_may_2013_to_2014.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '1' as period FROM misalignment_and_edits where revision_timestamp >= 20140500000000 and revision_timestamp < 20150500000000 AND page_views IS NOT NULL AND edit_type = 'bot_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_bot_edits_may_2014_to_2015.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '1' as period FROM misalignment_and_edits where revision_timestamp >= 20150500000000 and revision_timestamp < 20160500000000 AND page_views IS NOT NULL AND edit_type = 'bot_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_bot_edits_may_2015_to_2016.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '1' as period FROM misalignment_and_edits where revision_timestamp >= 20160500000000 and revision_timestamp < 20170500000000 AND page_views IS NOT NULL AND edit_type = 'bot_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_bot_edits_may_2016_to_2017.tsv';

# Human edits
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '2' as period FROM misalignment_and_edits where revision_timestamp >= 20130500000000 and revision_timestamp < 20140500000000 AND page_views IS NOT NULL AND edit_type = 'human_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_human_edits_may_2013_to_2014.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '2' as period FROM misalignment_and_edits where revision_timestamp >= 20140500000000 and revision_timestamp < 20150500000000 AND page_views IS NOT NULL AND edit_type = 'human_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_human_edits_may_2014_to_2015.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '2' as period FROM misalignment_and_edits where revision_timestamp >= 20150500000000 and revision_timestamp < 20160500000000 AND page_views IS NOT NULL AND edit_type = 'human_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_human_edits_may_2015_to_2016.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '2' as period FROM misalignment_and_edits where revision_timestamp >= 20160500000000 and revision_timestamp < 20170500000000 AND page_views IS NOT NULL AND edit_type = 'human_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_human_edits_may_2016_to_2017.tsv';

# Anon edits
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '3' as period FROM misalignment_and_edits where revision_timestamp >= 20130500000000 and revision_timestamp < 20140500000000 AND page_views IS NOT NULL AND edit_type = 'anon_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_anon_edits_may_2013_to_2014.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '3' as period FROM misalignment_and_edits where revision_timestamp >= 20140500000000 and revision_timestamp < 20150500000000 AND page_views IS NOT NULL AND edit_type = 'anon_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_anon_edits_may_2014_to_2015.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '3' as period FROM misalignment_and_edits where revision_timestamp >= 20150500000000 and revision_timestamp < 20160500000000 AND page_views IS NOT NULL AND edit_type = 'anon_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_anon_edits_may_2015_to_2016.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '3' as period FROM misalignment_and_edits where revision_timestamp >= 20160500000000 and revision_timestamp < 20170500000000 AND page_views IS NOT NULL AND edit_type = 'anon_edit') TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_anon_edits_may_2016_to_2017.tsv';

# Tool edits
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '4' as period FROM misalignment_and_edits where revision_timestamp >= 20130500000000 and revision_timestamp < 20140500000000 AND page_views IS NOT NULL AND (edit_type != 'bot_edit' AND edit_type != 'human_edit' AND edit_type != 'anon_edit')) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_tool_edits_may_2013_to_2014.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '4' as period FROM misalignment_and_edits where revision_timestamp >= 20140500000000 and revision_timestamp < 20150500000000 AND page_views IS NOT NULL AND (edit_type != 'bot_edit' AND edit_type != 'human_edit' AND edit_type != 'anon_edit')) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_tool_edits_may_2014_to_2015.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '4' as period FROM misalignment_and_edits where revision_timestamp >= 20150500000000 and revision_timestamp < 20160500000000 AND page_views IS NOT NULL AND (edit_type != 'bot_edit' AND edit_type != 'human_edit' AND edit_type != 'anon_edit')) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_tool_edits_may_2015_to_2016.tsv';
\copy (SELECT misalignment_year, misalignment_month, namespace, page_title, edit_type, page_views, revision_id, '4' as period FROM misalignment_and_edits where revision_timestamp >= 20160500000000 and revision_timestamp < 20170500000000 AND page_views IS NOT NULL AND (edit_type != 'bot_edit' AND edit_type != 'human_edit' AND edit_type != 'anon_edit')) TO '/export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_edit_types_tables_and_queries/used_tool_edits_may_2016_to_2017.tsv';
