set misalignment_and_edits_table_directory = /export/scratch2/wmf/scripts/wikidata_usage_tracking/sql_scripts/postgres/wikidata_page_revisions_with_timestamp_table/wikidata_page_revisions_bot_info_table/wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_table/wikidata_page_revisions_with_timestamp_edit_types_and_usage_table/entity_edit_types_sparse_and_usage_table/misalignment_and_edits_table

set misalignment_and_edits_sql_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/misalignment_and_edits
set misalignment_and_edits_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/misalignment_and_edits


echo "Running 'misalignment_and_edits' table queries"
source $misalignment_and_edits_table_directory/queries/all_queries.sh


rm -f $misalignment_and_edits_results_directory/wasted_edits_error_log.tsv
python /export/scratch2/wmf/scripts/wikidata_usage_tracking/python_analysis_scripts/wasted_edit_analysis/wasted_edit_analysis.py \
$misalignment_and_edits_sql_results_directory/monthly_misalignment_and_edits_ordered_by_entity_year_month.tsv \
$misalignment_and_edits_results_directory/misalignment_and_edits/wasted_edits.tsv \
--verbose \
> & $misalignment_and_edits_results_directory/wasted_edits_error_log.tsv