wget -r -o wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2016-05/ https://dumps.wikimedia.org/other/pageviews/2016/2016-05/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2016-06/ https://dumps.wikimedia.org/other/pageviews/2016/2016-06/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2016-07/ https://dumps.wikimedia.org/other/pageviews/2016/2016-07/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2016-08/ https://dumps.wikimedia.org/other/pageviews/2016/2016-08/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2016-09/ https://dumps.wikimedia.org/other/pageviews/2016/2016-09/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2016-10/ https://dumps.wikimedia.org/other/pageviews/2016/2016-10/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2016-11/ https://dumps.wikimedia.org/other/pageviews/2016/2016-11/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2016-12/ https://dumps.wikimedia.org/other/pageviews/2016/2016-12/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2017-01/ https://dumps.wikimedia.org/other/pageviews/2017/2017-01/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2017-02/ https://dumps.wikimedia.org/other/pageviews/2017/2017-02/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2017-03/ https://dumps.wikimedia.org/other/pageviews/2017/2017-03/ &&
wget -r -a wikipedia_page_view_download_error_log.txt -nv --no-parent --reject html --accept-regex "pageview" -nd -P ../wikipedia_page_view_dumps/2017-04/ https://dumps.wikimedia.org/other/pageviews/2017/2017-04/