CREATE TABLE misalignment_and_edits AS (
SELECT misalignment.entity_id, misalignment.year, misalignment.month, quality_class, views_class, bot_edits, semi_automated_edits, non_bot_edits, anon_edits, anon_ten_recall_bot_edit, anon_twenty_recall_bot_edit, anon_thirty_recall_bot_edit, anon_forty_recall_bot_edit, anon_fifty_recall_bot_edit, anon_sixty_recall_bot_edit, anon_seventy_recall_bot_edit, anon_eighty_recall_bot_edit, anon_ninety_recall_bot_edit, anon_one_hundred_recall_bot_edit, total_bot_edits, total_semi_automated_edits, total_non_bot_edits, total_anon_edits, total_anon_ten_recall_bot_edit, total_anon_twenty_recall_bot_edit, total_anon_thirty_recall_bot_edit, total_anon_forty_recall_bot_edit, total_anon_fifty_recall_bot_edit, total_anon_sixty_recall_bot_edit, total_anon_seventy_recall_bot_edit, total_anon_eighty_recall_bot_edit, total_anon_ninety_recall_bot_edit, total_anon_one_hundred_recall_bot_edit
FROM used_entity_previous_month_edits 
INNER JOIN misalignment 
ON misalignment.entity_id = used_entity_previous_month_edits.entity_id 
	AND misalignment.year = used_entity_previous_month_edits.year 
	AND misalignment.month = used_entity_previous_month_edits.month
);




	

	