CREATE INDEX revision_timestamp_index ON wikidata_page_revisions_with_timestamp(revision_timestamp);
CREATE INDEX page_title_index ON wikidata_page_revisions_with_timestamp(page_title);
CREATE INDEX revision_id_index ON wikidata_page_revisions_with_timestamp(revision_id);
CREATE INDEX user_index ON wikidata_page_revisions_with_timestamp(revision_user);
CREATE INDEX comment_index ON wikidata_page_revisions_with_timestamp(comment);
