CREATE TABLE entity_revisions_and_types_and_usages_and_bot_pred_sparse AS (
	SELECT year_month_page_title, page_views, number_of_revisions, page_title, year, month, namespace, anon_edits, bot_edits, human_edits, semi_automated_edits, anon_ten_recall_bot_edit, anon_twenty_recall_bot_edit, anon_thirty_recall_bot_edit, anon_forty_recall_bot_edit, anon_fifty_recall_bot_edit, anon_sixty_recall_bot_edit, anon_seventy_recall_bot_edit, anon_eighty_recall_bot_edit, anon_ninety_recall_bot_edit, anon_one_hundred_recall_bot_edit
	FROM entity_revisions_and_types_and_usages_and_bot_pred_sparse_sub_table_1
	UNION ALL
	SELECT year_month_page_title, page_views, number_of_revisions, page_title, year, month, namespace, anon_edits, bot_edits, human_edits, semi_automated_edits, anon_ten_recall_bot_edit, anon_twenty_recall_bot_edit, anon_thirty_recall_bot_edit, anon_forty_recall_bot_edit, anon_fifty_recall_bot_edit, anon_sixty_recall_bot_edit, anon_seventy_recall_bot_edit, anon_eighty_recall_bot_edit, anon_ninety_recall_bot_edit, anon_one_hundred_recall_bot_edit
	FROM entity_revisions_and_types_and_usages_and_bot_pred_sparse_sub_table_2
	UNION ALL
	SELECT year_month_page_title, page_views, number_of_revisions, page_title, year, month, namespace, anon_edits, bot_edits, human_edits, semi_automated_edits, anon_ten_recall_bot_edit, anon_twenty_recall_bot_edit, anon_thirty_recall_bot_edit, anon_forty_recall_bot_edit, anon_fifty_recall_bot_edit, anon_sixty_recall_bot_edit, anon_seventy_recall_bot_edit, anon_eighty_recall_bot_edit, anon_ninety_recall_bot_edit, anon_one_hundred_recall_bot_edit
	FROM entity_revisions_and_types_and_usages_and_bot_pred_sparse_sub_table_3
	UNION ALL
	SELECT year_month_page_title, page_views, number_of_revisions, page_title, year, month, namespace, anon_edits, bot_edits, human_edits, semi_automated_edits, anon_ten_recall_bot_edit, anon_twenty_recall_bot_edit, anon_thirty_recall_bot_edit, anon_forty_recall_bot_edit, anon_fifty_recall_bot_edit, anon_sixty_recall_bot_edit, anon_seventy_recall_bot_edit, anon_eighty_recall_bot_edit, anon_ninety_recall_bot_edit, anon_one_hundred_recall_bot_edit
	FROM entity_revisions_and_types_and_usages_and_bot_pred_sparse_sub_table_4
	UNION ALL
	SELECT year_month_page_title, page_views, number_of_revisions, page_title, year, month, namespace, anon_edits, bot_edits, human_edits, semi_automated_edits, anon_ten_recall_bot_edit, anon_twenty_recall_bot_edit, anon_thirty_recall_bot_edit, anon_forty_recall_bot_edit, anon_fifty_recall_bot_edit, anon_sixty_recall_bot_edit, anon_seventy_recall_bot_edit, anon_eighty_recall_bot_edit, anon_ninety_recall_bot_edit, anon_one_hundred_recall_bot_edit
	FROM entity_revisions_and_types_and_usages_and_bot_pred_sparse_sub_table_5
);