# Have been running python scripts in the virtual environment on flagon here: /export/scratch2/wmf/scripts/

set wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_table_directory = /export/scratch2/wmf/scripts/wikidata_usage_tracking/sql_scripts/postgres/wikidata_page_revisions_with_timestamp_table/wikidata_page_revisions_bot_info_table/wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_table
set entity_monthly_types_of_semi_automated_edits_table_directory = $wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_table_directory/used_entity_previous_month_edits_table
set wikidata_page_revisions_with_timestamp_edit_types_and_usage_table_directory = $wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_table_directory/misalignment_and_edits_table

set wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_sql_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/sql_queries/wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags
set wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_processing_results_directory = /export/scratch2/wmf/wbc_entity_usage/usage_results/wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags


source $wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_table_directory/queries/all_queries.sh

# Create (drop old tables if need be) directly dependent tables

psql wikidata_entities -c "drop entity_monthly_types_of_semi_automated_edits;"
psql wikidata_entities < $entity_monthly_types_of_semi_automated_edits/table_creation.sql

psql wikidata_entities -c "drop table wikidata_page_revisions_with_timestamp_edit_types_and_usage;"
psql wikidata_entities < $wikidata_page_revisions_with_timestamp_edit_types_and_usages_table_directory/table_creation.sql

# Run dependencies

source $entity_monthly_types_of_semi_automated_edits_table_directory/all_dependencies.sh
source $wikidata_page_revisions_with_timestamp_edit_types_and_usage_table_directory/all_dependencies.sh