set misalignment_and_edits_table_queries_directory = /export/scratch2/wmf/scripts/wikidata_usage_tracking/sql_scripts/postgres/wikidata_page_revisions_with_timestamp_table/wikidata_page_revisions_bot_info_table/wikidata_page_revisions_with_timestamp_bot_and_tool_change_tags_table/wikidata_page_revisions_with_timestamp_edit_types_and_usage_table/entity_edit_types_sparse_and_usage_table/misalignment_and_edits_table/queries

psql wikidata_entities < $misalignment_and_edits_table_queries_directory/anon_revision_alignment.sql
psql wikidata_entities < $misalignment_and_edits_table_queries_directory/monthly_edit_types.sql
psql wikidata_entities < $misalignment_and_edits_table_queries_directory/monthly_misalignment_and_edits_ordered_by_entity_year_month.sql
psql wikidata_entities < $misalignment_and_edits_table_queries_directory/edit_proportions_by_entity_views_5_17.sql
psql wikidata_entities < $misalignment_and_edits_table_queries_directory/edit_proportions_by_quality_and_view_class_5_17.sql
psql wikidata_entities < $misalignment_and_edits_table_queries_directory/edit_proportions_by_quality_class_5_17.sql