CREATE INDEX entity_revisions_index_revision_timestamp ON entity_revisions(revision_timestamp);
CREATE INDEX entity_revisions_index_page_title ON entity_revisions(page_title);
CREATE INDEX entity_revisions_index_revision_id ON entity_revisions(revision_id);
CREATE INDEX entity_revisions_index_revision_user ON entity_revisions(revision_user);
CREATE INDEX entity_revisions_index_comment ON entity_revisions(comment);
